### ISSUE TITLE
Milestone 1 feedback

### ISSUE THREAD

**Issue by gubbelcn** [UBC-MDS/obesity-explorer#40]
Hey Group 1,

Congrats on completing your eponymous milestone! You're off to a great start. Your proposal was well done overall and was quite well written (just watch out for typos). The main note I'd make is that while the usage scenario was well written, merging the following bullets directly into the text would've made things a bit more cohesive. Some parts could also have been a bit more concise.

With regards to your dashboard:
- The plan seems solid and like a reasonable amount of work for the final project. That said, you may want to start with only one plot in the bottom left for milestone 2 (for the sake of time).
- Since your main focus is obesity, will those bottom left plots stay the same as you change the factor? Or will they also change? This isn't clear to me from your description.
- It's also not clear to me how exactly the aggregation feature will be used, this could be explained a bit more explicitly
- Finally, as you develop your dashboard from this sketch, be sure to give some thought to the layout of the panels themselves and what will make the most efficient use of space without overcrowding. At the moment this feels simultaneously a bit crowded and a bit wasteful of space (due to aspect ratios and such)

**Comment by jraza19** [comment]
Checklist of feedback (come back and add issue numbers once addressed):

- [x] Change the three bottom left plots to one plot - [Add the factor plot and combined all plots #49](https://github.com/UBC-MDS/obesity-explorer/pull/49/commits/405a47a65085cd5d3d8869ae5b9753459826457b)
- [x] Ensure bottom left plots change through user input - [Add the factor plot and combined all plots #49](https://github.com/UBC-MDS/obesity-explorer/pull/49/commits/405a47a65085cd5d3d8869ae5b9753459826457b)
- [x] Add an aggregation feature and explain its functionality more clearly in the proposal/dashboard - [additional context to aggregation plots #46](https://github.com/UBC-MDS/obesity-explorer/pull/46) 
- [x] Ensure a layout with a good amount of whitespace - see app!

**Comment by jraza19** [comment]
Reopening issue to ensure that TA is able to see the issue.

**Comment by rtaph** [comment]
Closing this issue as this feedback was integrated.
