### ISSUE TITLE
Milestone 2 Checklist

### ISSUE THREAD

**Issue by dusty736** [UBC-MDS/obesity-explorer#42]
- [x] Incorporate Milestone 1 feedback (Dustin - PR in)

- [x] Canvas submission.html (Javairia)

- [x] Heroku link added to READMD.md (Tanmay)

- [x] Implemented correct file structure (Dustin)

- [x] Create environment.yaml file (Raf): See #44

- [x] Move proposal to doc folder (Javairia)

- [x] Dashboard documentation (Raf)

- [x] Reflection document (Group)

- [x] Add documentation to functions in src/app.py (Tanmay)

- [x] Improve the readme (optional)

- [x] Make GIF of prototype and add to README (Raf): See #45

**Comment by dusty736** [comment]
Milestone submitted.
